[package]
name = "texty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
errno = "0.3.8"
log = "0.4.20"
log4rs = "1.2.0"
num = "0.4.1"
